[versions]
agp = "8.13.1"
kotlin = "2.2.21"
kotlinx-serialization = "1.9.0"
kotlinx-coroutines = "1.10.2"
coreKtx = "1.17.0"
junit = "4.13.2"
junitVersion = "1.3.0"
espressoCore = "3.7.0"
lifecycleRuntimeKtx = "2.10.0"
activityCompose = "1.12.0"
composeBom = "2025.11.01"
navigationCompose = "2.9.6"
jetbrainsKotlinJvm = "2.2.21"
ksp = "2.3.3"
dagger = "2.57.2"
hiltNavigationCompose = "1.3.0"
appcompat = "1.7.1"
material = "1.13.0"
constraintLayout = "2.2.1"
vbpd = "2.0.4"
splashscreen = "1.2.0"
hilt-extenions = "1.4.0"
retrofit = "3.0.0"
okHttp = "5.3.2"
room = "2.8.4"
security = "1.1.0"
lifecycle = "2.10.0"
icons = "1.7.8"

[libraries]
# Only for build-src
kotlin-gradlePlugin = { module = "org.jetbrains.kotlin:kotlin-gradle-plugin", version.ref = "kotlin" }
android-gradlePlugin = { module = "com.android.tools.build:gradle", version.ref = "agp" }

# Kotlin
## Serialization
kotlinx-serialization = { module = "org.jetbrains.kotlinx:kotlinx-serialization-json", version.ref = "kotlinx-serialization" }
## Coroutines
kotlinx-coroutines-core = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-core", version.ref = "kotlinx-coroutines" }
kotlinx-coroutines-android = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "kotlinx-coroutines" }

# UIComponents
androidx-compose-bom = { group = "androidx.compose", name = "compose-bom", version.ref = "composeBom" }
androidx-compose-ui = { group = "androidx.compose.ui", name = "ui" }
androidx-compose-ui-graphics = { group = "androidx.compose.ui", name = "ui-graphics" }
androidx-compose-ui-tooling = { group = "androidx.compose.ui", name = "ui-tooling" }
androidx-compose-ui-tooling-preview = { group = "androidx.compose.ui", name = "ui-tooling-preview" }
androidx-compose-material3 = { group = "androidx.compose.material3", name = "material3" }
androidx-compose-material-icons = { group = "androidx.compose.material", name = "material-icons-extended", version.ref ="icons" }
androidx-appcompat = { group = "androidx.appcompat", name = "appcompat", version.ref = "appcompat" }
material = { group = "com.google.android.material", name = "material", version.ref = "material" }
androidx-constraintLayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintLayout" }
viewbinding-propertydelegate = { module = "dev.androidbroadcast.vbpd:vbpd", version.ref = "vbpd" }

# Tests
androidx-compose-ui-test-manifest = { group = "androidx.compose.ui", name = "ui-test-manifest" }
androidx-compose-ui-test-junit4 = { group = "androidx.compose.ui", name = "ui-test-junit4" }
junit = { group = "junit", name = "junit", version.ref = "junit" }

# Navigation
androidx-navigation-compose = { group = "androidx.navigation", name = "navigation-compose", version.ref = "navigationCompose" }

# Core
androidx-core-ktx = { group = "androidx.core", name = "core-ktx", version.ref = "coreKtx" }
androidx-core-splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashscreen" }

# Lifecycle
androidx-lifecycle-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel", version.ref = "lifecycle" }
androidx-lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime", version.ref = "lifecycle" }

# Javax
# [javax.inject package](https://docs.oracle.com/javaee/6/api/javax/inject/package-summary.html)
# [JSR-330](https://javax-inject.github.io/javax-inject/)
javax-inject = { module = "javax.inject:javax.inject", version = "1" }

# Hilt
hilt-android = { module = "com.google.dagger:hilt-android", version.ref = "dagger" }
hilt-compiler = { module = "com.google.dagger:hilt-compiler", version.ref = "dagger" }
hilt-navigation-compose = { module = "androidx.hilt:hilt-navigation-compose", version.ref = "hiltNavigationCompose" }
hilt-extensions = { module = "it.czerwinski.android.hilt:hilt-extensions", version.ref = "hilt-extenions" }
hilt-extensions-processor = { module = "it.czerwinski.android.hilt:hilt-processor-ksp", version.ref = "hilt-extenions" }

# Retrofit
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofit" }
retrofit-converter-kotlinx-serialization = { module = "com.squareup.retrofit2:converter-kotlinx-serialization", version.ref = "retrofit" }

# OkHttp
okHttp-bom = { module = "com.squareup.okhttp3:okhttp-bom", version.ref = "okHttp" }
okHttp = { module = "com.squareup.okhttp3:okhttp" }
okHttp-loggingInterceptor = { module = "com.squareup.okhttp3:logging-interceptor" }

# Room
androidx-room-runtime = { module = "androidx.room:room-runtime", version.ref = "room" }
androidx-room-compiler = { module = "androidx.room:room-compiler", version.ref = "room" }

# Security
androidx-security-crypto = { module = "androidx.security:security-crypto-ktx", version.ref = "security" }

[plugins]
# AGP - Android Gradle Plugin
android-application = { id = "com.android.application", version.ref = "agp" }
# Android
android-library = { id = "com.android.library", version.ref = "agp" }

# Kotlin
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlin" }
kotlin-compose = { id = "org.jetbrains.kotlin.plugin.compose", version.ref = "kotlin" }
kotlinx-serialization = { id = "org.jetbrains.kotlin.plugin.serialization", version.ref = "kotlin" }
jetbrains-kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "jetbrainsKotlinJvm" }

# KSP
ksp = { id = "com.google.devtools.ksp", version.ref = "ksp" }

# Hilt
hilt-android = { id = "com.google.dagger.hilt.android", version.ref = "dagger" }

# Conventions
convention-kotlin-library = { id = "kotlin-library-conventions", version = "1.0" }
convention-android-app = { id = "android-app-conventions", version = "1.0" }
convention-android-library = { id = "android-library-conventions", version = "1.0" }
